name 'puppet-statuswolf'
version '0.0.1'

author 'Markus Burger'
license 'Apache2'
project_page ''
source ''
summary 'Puppet module for statuswolf'
description 'This module installs and manages statuswolf. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
